import { icons } from "../assets/assets";
import { assets } from "../assets/assets";

export const blogs = [
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "We are the world leaders",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Serve your energy needs",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
  {
    thumbnail: assets.about_us_thumbnail1,
    title: "Helping the oil industry",
    desc: "Lorem ipsum dolor sit amet, consectetur tempor adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqa.Alias, voluptatibus? Pariatur, officia hic. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    date: "29/07/2024",
    category: "uncategorized",
  },
];

export const services = [
  {
    icon: icons.source_energy_icon,
    title: "Soucrce Energy",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida.",
  },
  {
    icon: icons.store_energy_icon,
    title: "Store Energy",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida.",
  },
  {
    icon: icons.sell_energy_icon,
    title: "Sell Energy",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida.",
  },
];
